### ISSUE TITLE
Error on exit from exec docker.

### ISSUE THREAD

**Issue by sfister** [metocean/ducke#7]
exiting a docker connection from an exec command throws and exception:

"
exit

/usr/local/lib/node_modules/ducke/src/ducke.js:269
                  stdin.setRawMode(wasRaw);
                                   ^
ReferenceError: wasRaw is not defined
    at HttpDuplex.<anonymous> (/usr/local/lib/node_modules/ducke/src/ducke.js:269:36)
    at HttpDuplex.emit (events.js:117:20)
    at /usr/local/lib/node_modules/ducke/node_modules/ducke-modem/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
"

**Comment by tcoats** [comment]
This seems very similar to a bug I fixed lately. What version of ducke are you running? If you run the following it should tell you. `2.3.8` is the latest at the moment.

```sh
cat /usr/local/lib/node_modules/ducke/package.json | grep version
```

**Comment by sfister** [comment]
I was running on 2.3.7.  I upgraded to 2.3.8 and still have the issue.

**Comment by tcoats** [comment]
I've released 2.3.9 just in case I didn't release the changes in 2.3.8.

Are you able to paste the new exception stack trace?
Both 2.3.8 and 2.3.9 should have a different stack trace if they are still erroring. Cheers!

**Comment by sfister** [comment]
2.3.9 exception stack:
/usr/local/lib/node_modules/ducke/src/ducke.js:269
                  stdin.setRawMode(wasRaw);
                                   ^
ReferenceError: wasRaw is not defined
    at HttpDuplex.<anonymous> (/usr/local/lib/node_modules/ducke/src/ducke.js:269:36)
    at HttpDuplex.emit (events.js:117:20)
    at /usr/local/lib/node_modules/ducke/node_modules/ducke-modem/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)

**Comment by sfister** [comment]
I have just uninstalled and reinstalled both ducke and tugboat with the same results.

**Comment by tcoats** [comment]
Groovy, we sorted it out :smiley:
